import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MintView from '../components/MintView'
import styles from '../styles/Home.module.css'
import { useWallet } from '@solana/wallet-adapter-react'

const Home: NextPage = () => {
  const data = useWallet()

  return (
    <div className={styles.container}>
      <Head>
        <title>Sad Boiz</title>
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="home" className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a style={{color:"#553561"}}>Sad Boiz!</a>
        </h1>
      </main>

      <div id="mintView">
        <MintView/>
      </div>
      
      <div id="story" className={styles.main}>
        <h1 className="mint-title">
          Story Section
        </h1>
      </div>

      <div id="faq" className={styles.main}>
        <h1 className="mint-title">
          FAQ Section
        </h1>
      </div>

      <div id="contact" className={styles.main}>
        <h1 className="mint-title">
          Contact Section
        </h1>
      </div>


      <footer className={styles.footer}>
        <a>Powered by: </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <a
          href="https://solana.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo} >
            <Image src="/solanaWordMark.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
